version: "3.1"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - 5000:80
      - 25:25
      - 143:143
